# Generated by Django 4.2.30 on 2026-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_type', models.CharField(choices=[('private', 'Приватна особа'), ('company', 'Компанія')], default='private', max_length=10)),
                ('name_company', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('User', 'Користувач'), ('Employer', 'Роботодавець'), ('Admin', 'Адміністратор')], default='Employer', max_length=20)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('hq_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Головний офіс (Місто, Країна)')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='imge_avatar')),
                ('op', models.CharField(blank=True, choices=[('Yes', 'Так'), ('No', 'Ні')], default='Yes', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last_name')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='patronymic')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Чоловік'), ('Women', 'Жінка')], default='Ч', max_length=20)),
                ('role', models.CharField(choices=[('User', 'Користувач'), ('Employer', 'Роботодавець'), ('Admin', 'Адміністратор')], default='User', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
