# Generated by Django 4.2.30 on 2026-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('User', 'Користувач'), ('Employer', 'Роботодавець'), ('Admin', 'Адміністратор')], default='User', max_length=20),
        ),
    ]
