# Generated by Django 4.2.30 on 2026-05-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_remove_userprofile_birth_year_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Men', 'Чоловік'), ('Women', 'Жінка')], default='Ч', max_length=20),
        ),
    ]
