# Generated by Django 4.2.30 on 2026-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='role',
            field=models.CharField(choices=[('User', 'Користувач'), ('Employer', 'Роботодавець'), ('Admin', 'Адміністратор')], default='Employer', max_length=20),
        ),
    ]
