# Generated by Django 4.2.30 on 2026-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_employerprofile_email_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
