# Generated by Django 4.2.30 on 2026-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_employerprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(choices=[('private', 'Приватна особа'), ('company', 'Компанія')], default='private', max_length=10),
        ),
    ]
