# Generated by Django 4.2.30 on 2026-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_employerprofile_employer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imge_avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='op',
            field=models.CharField(blank=True, choices=[('Yes', 'Так'), ('No', 'Ні')], default='Yes', max_length=20, null=True),
        ),
    ]
