# Generated by Django 4.2.30 on 2026-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_userprofile_avatar_userprofile_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='hq_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Головний офіс (Місто, Країна)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону'),
        ),
    ]
