# Generated by Django 4.2.30 on 2026-05-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_userprofile_gender'),
        ('chat', '0002_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_system.userprofile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_system.employerprofile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_system.employerprofile'),
        ),
    ]
