# Generated by Django 4.2.30 on 2026-05-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_userprofile_gender'),
        ('project', '0008_remove_vacancy_user'),
        ('chat', '0003_alter_chat_candidate_alter_chat_employer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chat',
            name='application',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='project.application'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('employer', 'candidate', 'application')},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='vacancy',
        ),
    ]
