# Generated by Django 4.2.30 on 2026-05-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_unique_together_chat_application_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='employer',
        ),
    ]
