# Generated by Django 4.2.30 on 2026-05-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_unique_together_remove_chat_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='author',
        ),
    ]
