# Generated by Django 4.2.30 on 2026-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
