# Generated by Django 4.2.30 on 2026-04-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_application_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='test_name',
        ),
    ]
