# Generated by Django 4.2.30 on 2026-06-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.city'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_res',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону'),
        ),
    ]
