# Generated by Django 4.2.30 on 2026-05-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_remove_userprofile_birth_year_userprofile_role'),
        ('project', '0003_remove_application_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='auth_system.employerprofile'),
        ),
    ]
