# Generated by Django 4.2.30 on 2026-04-24 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_response_unique_together_alter_response_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'response')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='vacancy',
        ),
    ]
