# Generated by Django 4.2.30 on 2026-05-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_delete_chat_vacancy_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('reject', 'Відхилено'), ('under_review', 'На розгляді'), ('accepted', 'Прийнято')], max_length=50, null=True),
        ),
    ]
