# Generated by Django 4.2.30 on 2026-05-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_vacancy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='user',
        ),
    ]
