# Generated by Django 4.2.30 on 2026-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_vacancy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('reject', 'Відхилено'), ('under_review', 'На розгляді'), ('accepted', 'Прийнято')], default='under_review', max_length=50, null=True),
        ),
    ]
