# Generated by Django 4.2.30 on 2026-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('under_review', 'На розгляді'), ('reject', 'Відхилено'), ('accepted', 'Прийнято')], default='under_review', max_length=50),
        ),
    ]
