# Generated by Django 4.2.30 on 2026-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
