# Generated by Django 4.2.30 on 2026-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_resume_description1_resume_description2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Повна зайнятість'), ('part_time', 'Неповна зайнятість')], default='full_time', max_length=20, verbose_name='Тип зайнятості'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('no_experience', 'Без досвіду'), ('experience', 'Досвід роботи')], default='no_experience', max_length=20, verbose_name='Досвід роботи'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(choices=[('office', 'В офісі'), ('remote', 'Віддалено'), ('hybrid', 'Гібрид')], default='office', max_length=20, verbose_name='Формат роботи'),
        ),
    ]
